version: '3.8'

services:
  # Frontend service for development
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - cloudfi-network

  # Backend service for development
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
    networks:
      - cloudfi-network

  # MySQL database service
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloudfi_dev
      MYSQL_USER: cloudfi_user
      MYSQL_PASSWORD: cloudfi_password
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - cloudfi-network

# Define networks
networks:
  cloudfi-network:
    driver: bridge

# Define volumes
volumes:
  mysql_data_dev: